### ISSUE TITLE
autoprogram -- module object has no attribute 'indent'

### ISSUE THREAD

**Issue by hackermd** [elcojacobs/sphinx-contrib#2]
The following line in the `autoprogram.py` module is not compatible with Python 2.7:

```python
yield textwrap.indent(usage, '    ')
```

because the [textwrap module in Python 2](https://docs.python.org/2/library/textwrap.html) doesn't have an `indent` function.

**Comment by elcojacobs** [comment]
I think you'll want to submit this here instead:

https://bitbucket.org/birkenfeld/sphinx-contrib/
